-- Seed events with mixed timing and capacity

INSERT INTO events (
    name,
    description,
    category,
    points,
    latitude,
    longitude,
    location_name,
    location_radius_meters,
    start_time,
    end_time,
    time_tolerance_minutes,
    status,
    created_by,
    capacity,
    is_personal
) VALUES
(
    'AI Product Sprint Camp',
    'Three-day sprint focused on building practical AI features with mentor check-ins and peer demos.',
    'technical',
    55,
    12.971598,
    77.594566,
    'Bangalore International Convention Centre',
    150,
    NOW() - INTERVAL '1 day',
    NOW() + INTERVAL '2 days',
    45,
    'active',
    1,
    120,
    false
),
(
    'Urban Safety Hack Lab',
    'Collaborative problem-solving lab on urban safety and assistive tech prototypes.',
    'professional',
    40,
    12.972442,
    77.580643,
    'IISc Bangalore',
    120,
    NOW() - INTERVAL '12 hours',
    NOW() + INTERVAL '2 days 12 hours',
    30,
    'active',
    1,
    NULL,
    false
),
(
    'Green Campus Cleanup',
    'Volunteer cleanup drive across the campus perimeter with waste segregation focus.',
    'community service',
    30,
    12.975413,
    77.592834,
    'Cubbon Park Main Entrance',
    200,
    NOW() + INTERVAL '1 day',
    NOW() + INTERVAL '1 day 4 hours',
    30,
    'active',
    1,
    80,
    false
),
(
    'Cultural Night Showcase',
    'Performances, stalls, and art exhibits featuring student cultural clubs.',
    'cultural',
    25,
    12.934533,
    77.610166,
    'Lalbagh Botanical Garden',
    180,
    NOW() + INTERVAL '2 days',
    NOW() + INTERVAL '2 days 5 hours',
    20,
    'active',
    1,
    300,
    false
),
(
    'Inter-College Badminton Open',
    'Team registrations open. Multiple courts with group stage and finals.',
    'sports',
    35,
    12.966847,
    77.580811,
    'Kanteerava Indoor Stadium',
    150,
    NOW() + INTERVAL '3 days',
    NOW() + INTERVAL '3 days 8 hours',
    30,
    'active',
    1,
    200,
    false
),
(
    'Blood Donation Camp',
    'Certified medical staff on site. Participation certificate provided.',
    'community service',
    45,
    12.958423,
    77.636619,
    'Koramangala Community Center',
    140,
    NOW() + INTERVAL '5 days',
    NOW() + INTERVAL '5 days 6 hours',
    30,
    'active',
    1,
    150,
    false
),
(
    'National Green Pledge Walk',
    'Student march and pledge ceremony with tree sapling distribution.',
    'national initiative',
    20,
    12.847178,
    77.663011,
    'Bannerghatta National Park',
    250,
    NOW() + INTERVAL '7 days',
    NOW() + INTERVAL '7 days 4 hours',
    30,
    'active',
    1,
    NULL,
    false
),
(
    'District Level Job Fair 2026',
    'District Level Job Fair organized by the Department of Skill Development, Entrepreneurship and Livelihood, Zilla Panchayat Udupi, and Taluk Panchayat Kundapur at Bhandarkar’s College, Kundapur. Candidates with 10th standard and above qualifications can participate with relevant documents.',
    'professional',
    35,
    13.632600,
    74.690800,
    'Bhandarkar’s College, Kundapur',
    150,
    '2026-04-02 09:00:00',
    '2026-04-02 16:00:00',
    30,
    'active',
    1,
    500,
    false
);
